import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/redux/Provider";
import { Toaster } from "react-hot-toast";
import Header from "@/components/common/Header";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Layout from "./page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Explore Kashmir",
  description: "Generated by Explore Kashmir",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <Toaster position="top-right" />

          <Layout children={children} />
        </body>
      </Providers>
    </html>
  );
}
